### ISSUE TITLE
ImportError: No module named 'code.mkf_internal'; 'code' is not a package when I try to make a simple test code

### ISSUE THREAD

**Issue by asmwarrior** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#138] opened 2017-02-10 14:28 UTC
Under Windows7 64bit, when I download the git master zip, and create a simple python test code(say, I have a.py file)
`from code.mkf_internal import plot_track`

 in spyder, I get such error message:
`ImportError: No module named 'code.mkf_internal'; 'code' is not a package`

But I have create the a.py file exactly in the root folder of the unzip file, which means there is a folder named "code".

So, I guess there are some modules named "code", I just looked at my python installation. (In-fact, I'm now using WinPython with python 3.4, but this issue also happens in Anaconda python 3.5).  There are a file named "code.py" in the standard installed python.
`E:\download\sci\WinPython-64bit-3.4.4.6Qt5\python-3.4.4.amd64\Lib\code.py`
Does this caused by this file? But it looks like Python 2.7 also have this exact code.py file under the `Lib` folder.

So, do I need to add the currently folder to the top of the PYTHONPATH? or `sys.pah`?

BTW: this issue does not happens in the Anaconda python 2.7.

**Comment by asmwarrior** [comment] 2017-02-10 15:12
The good news is that I can change the folder name `code` to `code`, and then adjust some code in the py files like `code1\mkf_internal.py`, change the file from

`import code.book_plots as bp`
to
`import code1.book_plots as bp`

Then, I don't see the error now. 
So, my question is: is this a name conflict?

**Comment by rlabbe** [comment] 2017-02-10 15:20
Wow, I have no idea. I was fighting a similar issue a week or two ago, where I could import from code with IPython, but not Python. I will investigate some more, and maybe a module rename is in the immediate future.

**Comment by asmwarrior** [comment] 2017-02-11 00:14
In my testing environment, either Python and IPython gives the same error message.
`ImportError: No module named 'code.mkf_internal'; 'code' is not a package`

Also, if I wrote a code in the editor:
```
import code
code.<TAB>
```
Then I get the auto suggestion list include something like: 
```
compile_command
interact
...
```
Then, I select `interact`.
When I click the context menu "go to definition", then the file `E:\download\sci\WinPython-64bit-3.4.4.6Qt5\python-3.4.4.amd64\Lib\code.py` is opened, and the cursor is located in the function definition of `interact`.

So, I suggest a rename of this module.

**Comment by da-phil** [comment] 2017-05-05 22:56
I faced the same problem and also solved it by changing `code` to `nb_code`.
`code` is a module within the Python Standard Library (see https://docs.python.org/2/library/code.html)
I run `grep` and `sed` within the main repository folder to replace `code` by `nb_code` in the `import` statements and also in *.py files which use `code` as folder name to avoid the module name conflict.
```
    $ grep -rl 'import code' * | xargs sed -i 's/import code/import nb_code/g
    $ grep -rl 'code/' * | xargs sed -i 's*code/*nb_code/*g
```

**Comment by asmwarrior** [comment] 2017-05-10 02:58
Good method. I think you can add a pull request, so that this could be a great contribution for the world.

**Comment by chirping78** [comment] 2017-05-11 07:15
After struggled with this problem several hours, I finally got the root cause.

For these who are impatient, this is a module search and load priority problem. i.e. the system 'code' module take the priority over the local one.

There are detail discussion in this SO thread:
http://stackoverflow.com/questions/8556514/python-imports-being-overridden-by-the-standard-library-python-2-4

I have a quick  and dirty code change in https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python/pull/147

You can try this whether fixed your problem. Of course, the final decision and fix position is up to rlabbe.

**Comment by rlabbe** [comment] 2017-05-11 20:15
Sorry for the long delay; I just pushed a fix for this.

**Closed by rlabbe** 2017-05-11 20:15 UTC
