### ISSUE TITLE
Documentation for Mode Transition Probability Matrix in IMM

### ISSUE THREAD

**Issue by rexnewman** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#314] opened 2019-10-21 16:23 UTC
In the mode transition probability matrix (M) of the IMM, entry *M[i, j]* is described as the probability of transitioning from mode *j*, at index *k-1*, to mode *i*, at index *k*. This seems to conflict with the descriptions I've seen elsewhere which describes *M[i, j]* in the opposite sense: the probability of transition from mode *i*, at index *k-1*, to mode *j*, at index *k*. See, for example:
* Bar-Shalom, Y., Xiao-Rong L., and Thiagalingam Kirubarajan. *Estimation with Applications to Tracking and Navigation*. New York: Wiley, p. 444, 2001.

This exists in both the *Adaptive Filtering* notebook and the **IMMEstimator** docstring.

**Comment by rlabbe** [comment] 2020-05-05 00:26
Correct. Duplicate of #271, so closing this one.

**Closed by rlabbe** 2020-05-05 00:26 UTC
